#!/bin/sh
set -e
TMP_DIR=$(mktemp -d -t ssshutdown.XXXXXX)

trap 'rm -rf "$TMP_DIR"' EXIT

git clone https://github.com/joshuacox/SSShutdown.git "$TMP_DIR/SSShutdown"
cd "$TMP_DIR/SSShutdown"
sudo make install
