#!/bin/bash
. $REPLACE_PREFIX_REPLACE/SSShutdown/lib/uuutil.bash
MAXFREQ=$(($(cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_max_freq)/4))
MINFREQ=$(cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_min_freq)
GOVERNOR=powersave

cpufreqqr $GOVERNOR $MAXFREQ $MINFREQ
