#!/bin/bash
. $REPLACE_PREFIX_REPLACE/SSShutdown/lib/uuutil.bash

MAXFREQ=$(cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_min_freq)
MINFREQ=$(cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_min_freq)
GOVERNOR=powersave

powertop_auto_tune
cpufreqqr $GOVERNOR $MAXFREQ $MINFREQ
